name: Integration Tests Frontend Local Mode

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      build_branch:
        required: true
        type: string
      istio_version:
        required: false
        type: string
        default: ""
      stern_logs:
        required: false
        type: boolean
        default: false

env:
  TARGET_BRANCH: ${{ inputs.target_branch }}

jobs:
  integration_tests_frontend_local:
    name: Cypress integration tests (Local Mode)
    runs-on: ubuntu-latest
    env:
      # Copied from: https://github.com/bahmutov/cypress-gh-action-split-install/blob/ca3916d4e7240ebdc337825d2d78eb354855464b/.github/workflows/tests.yml#L7-L11
      # prevents extra Cypress installation progress messages
      CI: 1
      # avoid warnings like "tput: No value for $TERM and no -T specified"
      TERM: xterm
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.build_branch }}

    # This caches the yarn deps but does not touch node_modules so it's still necessary
    # to run 'yarn install' later to link these into node_modules.
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: yarn
        cache-dependency-path: frontend/yarn.lock

    - name: Download go binary
      uses: actions/download-artifact@v4
      with:
        name: kiali
        path: ~/go/bin/

    - name: Ensure kiali binary is executable
      run: chmod +x ~/go/bin/kiali

    # Need to install frontend dependencies to run cypress tests.
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile

    # Build the integration framework
    - name: Build integration framework
      working-directory: ./kiali-integration-framework
      run: make build

    # Create local mode configuration
    - name: Create local config
      working-directory: ./kiali-integration-framework
      run: |
        cat > local-frontend-config.yaml << 'EOF'
        version: "1.0"
        cluster:
          provider: kind
          name: kiali-local-test
          version: "1.27.0"
          config:
            nodes: 1
        components:
          istio:
            type: istio
            version: "${{ inputs.istio_version || '1.20.0' }}"
            enabled: true
            config:
              profile: default
          kiali:
            type: kiali
            version: "1.73.0"
            enabled: true
            config:
              auth:
                strategy: "token"
              web_port: "3000"
          prometheus:
            type: prometheus
            version: "2.45.0"
            enabled: true
        tests:
          frontend-local:
            type: cypress
            enabled: true
            config:
              cypress:
                baseUrl: "http://localhost:3000"
                specPattern: "**/*.feature"
                workingDir: "./frontend"
                headless: true
                browser: "electron"
                defaultCommandTimeout: 40000
                requestTimeout: 15000
                responseTimeout: 15000
                pageLoadTimeout: 90000
                tags: ["@core", "@smoke"]
        global:
          logLevel: "info"
          timeout: 1800000000000
          verbose: true
        EOF

    # Run frontend integration tests (Local Mode) using the new integration framework
    - name: Run frontend integration tests (Local Mode)
      working-directory: ./kiali-integration-framework
      run: |
        ./build/kiali-test init --config local-frontend-config.yaml
        ./build/kiali-test up --config local-frontend-config.yaml
        ./build/kiali-test run frontend-local --config local-frontend-config.yaml

    - name: Get debug info when integration tests fail
      if: failure()
      run: |
        mkdir debug-output
        hack/ci-get-debug-info.sh --output-directory debug-output

    - name: Upload debug info artifact
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info-${{ github.job }}
        path: debug-output

    - name: Upload cypress screenshots when tests fail
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots-${{ github.job }}
        path: frontend/cypress/screenshots

    - name: Upload cypress videos when tests fail
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-videos-${{ github.job }}
        path: frontend/cypress/videos

    - name: Upload integration framework test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results-${{ github.job }}
        path: kiali-integration-framework/test-results/

    - name: Upload cypress logs from stern
      uses: actions/upload-artifact@v4
      if: ${{ inputs.stern_logs == true }}
      with:
        name: cypress-logs-${{ github.job }}
        path: hack/stern
