name: Test Istio Version

on:
  workflow_dispatch:
    inputs:
      istio_version:
        description: "The version of Istio to test with. Format is either #.#.# or #.#-dev"
        required: true
        type: string
      branch_to_test:
        description: "The branch to build and test."
        required: true
        default: "master"
        type: string

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    outputs:
      target-branch: ${{ inputs.branch_to_test }}
      build-branch: ${{ inputs.branch_to_test }}
      istio-version: ${{ inputs.istio_version }}
    steps:
      # The initialize job gathers variables for later use in jobs.
      - run: echo "target-branch -> ${{ inputs.branch_to_test }}"
      - run: echo "build-branch -> ${{ inputs.branch_to_test }}"
      - run: echo "istio-version -> ${{ inputs.istio_version }}"

  build_backend:
    name: Build backend
    uses: ./.github/workflows/build-backend.yml
    needs: [initialize]
    with:
      build_branch: ${{ needs.initialize.outputs.build-branch }}

  build_frontend:
    name: Build frontend
    uses: ./.github/workflows/build-frontend.yml
    needs: [initialize]
    with:
      target_branch: ${{ needs.initialize.outputs.target-branch }}
      build_branch: ${{ needs.initialize.outputs.build-branch }}

  integration_tests_backend:
    name: Run backend integration tests
    uses: ./.github/workflows/integration-tests-backend.yml
    needs: [initialize, build_backend, build_frontend]
    with:
      target_branch: ${{ needs.initialize.outputs.target-branch }}
      build_branch: ${{ needs.initialize.outputs.build-branch }}
      istio_version: ${{ needs.initialize.outputs.istio-version }}

  integration_tests_frontend:
    name: Run frontend integration tests
    uses: ./.github/workflows/integration-tests-frontend.yml
    needs: [initialize, build_backend, build_frontend]
    with:
      target_branch: ${{ needs.initialize.outputs.target-branch }}
      build_branch: ${{ needs.initialize.outputs.build-branch }}
      istio_version: ${{ needs.initialize.outputs.istio-version }}

  integration_tests_frontend_multicluster:
    name: Run frontend multicluster integration tests
    uses: ./.github/workflows/integration-tests-frontend-multicluster.yml
    needs: [initialize, build_backend, build_frontend]
    with:
      target_branch: ${{ needs.initialize.outputs.target-branch }}
      build_branch: ${{ needs.initialize.outputs.build-branch }}
      istio_version: ${{ needs.initialize.outputs.istio-version }}
